violation_detection/Interface/urls.py
from django.contrib import admin
from django.urls import path

# from . import views
from . import views

app_name = 'Interface'

urlpatterns = [
    path('show/', views.show),
    path('prediction/', views.vehicle_model, name='prediction'),
    path('get_frames/', views.get_frames, name='get_frames'),
    path('get_first_response/', views.get_first_response, name='get_first_response'),
]

violation_detection/violation_detection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('view/', include('Interface.urls')),
]

violation_detection/Interface/models.py
from django.db import models


# Create your models here.


class Vehicle(models.Model):
    number = models.CharField(max_length=15, null=True, blank=True)
    mobile = models.PositiveIntegerField(default='8554951545')
    address = models.CharField(max_length=250, default='test')
    type = models.CharField(max_length=100)
    image_path = models.CharField(max_length=500)
    rc_path = models.CharField(max_length=500)
    is_done = models.BooleanField(default=False)


class Camera(models.Model):
    location = models.CharField(max_length=100)
    serial_number = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)


class Violation(models.Model):
    description = models.CharField(max_length=200)
    fine_amount = models.CharField(max_length=100)


class VehicleViolation(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    violation = models.ForeignKey(Violation, on_delete=models.CASCADE)
    timestamp = models.DateTimeField()
    has_paid = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

# class Config(models.Model):
#     graph_path =

violation_detection/Interface/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
import os
from PIL import Image
import numpy as np
import cv2
import copy

# from Interface.object_detection.config import *

import tensorflow as tf

from object_detection.config import *
from object_detection.functions import download_graph, load_image_into_numpy_array, \
    count_frames_manual
from object_detection.utils import label_map_util
from object_detection.utils.ops import reframe_box_masks_to_image_masks
from object_detection.utils.visualization_utils import visualize_boxes_and_labels_on_image_array

from .models import Vehicle

frames_done = 0
total_frames = 0


# from

# Create your views here.
def show(request):
    return render(request, 'home.html')


def vehicle_model(request):
    current_model = int(request.POST.get('model_name'))
    if to_download:
        download_graph(model['download_base_url'], model['file'])

    # Load Prediction
    detection_graph = tf.Graph()
    with detection_graph.as_default():
        od_graph_def = tf.GraphDef()
        # print(os.path.exists(model['path']))
        with tf.gfile.GFile(model['path'], 'rb') as fid:
            serialized_graph = fid.read()
            od_graph_def.ParseFromString(serialized_graph)
            tf.import_graph_def(od_graph_def, name='')

    label_map = label_map_util.load_labelmap(model['label'])
    categories = label_map_util.convert_label_map_to_categories(label_map,
                                                                max_num_classes=maximum_classes_to_detect,
                                                                use_display_name=True)
    category_index = label_map_util.create_category_index(categories)

    frames = 0
    vidcap = 0
    base_dir = ''
    counter = 0

    write_video_feed = ''

    if is_image:
        base_dir = path['image_dir']
        if current_model == 1:
            all_images = os.listdir(base_dir)
        elif current_model == 2:
            all_images = list(Vehicle.objects.filter(is_done=False).values_list('image_path', flat=True))

        global total_frames
        total_frames = len(all_images)


    else:
        video_path = path['video_dir']
        video_name = path['video_name']
        video_full = os.path.join(video_path, video_name)
        print(video_path)
        if not os.path.exists(path['output_video_dir']):
            os.makedirs(path['output_video_dir'])
        vidcap = cv2.VideoCapture(video_full)
        frames = count_frames_manual(vidcap)
        print('total frmames', frames)
        all_images = range(frames)
        global total_frames
        total_frames = len(all_images)
        vidcap.release()
        vidcap = cv2.VideoCapture(video_full)
        frame_width = int(vidcap.get(3))
        frame_height = int(vidcap.get(4))
        fps = vidcap.get(cv2.CAP_PROP_FPS)
        fps_int = int(round(fps))
        write_video_feed = cv2.VideoWriter(
            os.path.join(path['output_video_dir'], path['output_video_name']),
            cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'),
            fps_int,
            (frame_width, frame_height))
    with detection_graph.as_default():
        with tf.Session() as sess:
            for each_image in all_images:
                global frames_done
                frames_done = all_images.index(each_image)
                if is_image:
                    if current_model == 1:
                        image_path = os.path.join(base_dir, each_image)
                    else:
                        image_path = each_image
                    image = Image.open(image_path)
                    image_np = load_image_into_numpy_array(image)
                else:
                    rev, image_np = vidcap.read()
                # the array based representation of the image will be used later in order to prepare the
                # result image with boxes and labels on it.
                # Expand dimensions since the Prediction expects images to have shape: [1, None, None, 3]
                image_np_expanded = np.expand_dims(image_np, axis=0)
                # Actual detection.

                ops = tf.get_default_graph().get_operations()
                all_tensor_names = {output.name for op in ops for output in op.outputs}
                tensor_dict = {}
                for key in [
                    'num_detections', 'detection_boxes', 'detection_scores',
                    'detection_classes', 'detection_masks'
                ]:
                    tensor_name = key + ':0'
                    if tensor_name in all_tensor_names:
                        tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(
                            tensor_name)
                if 'detection_masks' in tensor_dict:
                    # The following processing is only for single image
                    detection_boxes = tf.squeeze(tensor_dict['detection_boxes'], [0])
                    detection_masks = tf.squeeze(tensor_dict['detection_masks'], [0])
                    # Reframe is required to translate mask from box coordinates to image coordinates and fit the image size.
                    real_num_detection = tf.cast(tensor_dict['num_detections'][0], tf.int32)
                    detection_boxes = tf.slice(detection_boxes, [0, 0], [real_num_detection, -1])
                    detection_masks = tf.slice(detection_masks, [0, 0, 0], [real_num_detection, -1, -1])
                    detection_masks_reframed = reframe_box_masks_to_image_masks(
                        detection_masks, detection_boxes, image_np.shape[0], image_np.shape[1])
                    detection_masks_reframed = tf.cast(
                        tf.greater(detection_masks_reframed, 0.5), tf.uint8)
                    # Follow the convention by adding back the batch dimension
                    tensor_dict['detection_masks'] = tf.expand_dims(
                        detection_masks_reframed, 0)
                image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')

                # Run inference
                output_dict = sess.run(tensor_dict,
                                       feed_dict={image_tensor: np.expand_dims(image_np, 0)})

                # all outputs are float32 numpy arrays, so convert types as appropriate
                output_dict['num_detections'] = int(output_dict['num_detections'][0])
                output_dict['detection_classes'] = output_dict[
                    'detection_classes'][0].astype(np.uint8)
                output_dict['detection_boxes'] = output_dict['detection_boxes'][0]
                output_dict['detection_scores'] = output_dict['detection_scores'][0]
                if 'detection_masks' in output_dict:
                    output_dict['detection_masks'] = output_dict['detection_masks'][0]

                image_np_copy = copy.deepcopy(image_np)
                if show_labels:
                    visualize_boxes_and_labels_on_image_array(
                        image_np_copy,
                        output_dict['detection_boxes'],
                        output_dict['detection_classes'],
                        output_dict['detection_scores'],
                        category_index,
                        instance_masks=output_dict.get('detection_masks'),
                        use_normalized_coordinates=True,
                        line_thickness=8,
                        min_score_thresh=min_score_thresh, )

                number = min(minimum_detection, output_dict['num_detections'])
                if current_model == 2:
                    number = 1
                print(number)
                print(current_model == 1)
                # print('current_model0', current_model, '\n')
                for i in range(number):
                    print(output_dict['detection_scores'][i])
                    if output_dict['detection_scores'][i] >= min_score_thresh:
                        class_name = category_index[output_dict['detection_classes'][i]]['name']
                        # print(class_name,categories)
                        if detect_all_categories == False and not {'name': class_name,
                                                                   'id': output_dict['detection_classes'][
                                                                       i]} in categories:
                            # print('Skipping')
                            continue
                        base_path = os.path.join(path['output_image_dir'], class_name)

                        if current_model == 1:
                            # print('It is one')
                            curr_vehicle_obj = Vehicle.objects.create(type=class_name)

                            current_name = str(curr_vehicle_obj.pk) + '_vehicle.jpg'
                            curr_vehicle_obj.image_path = os.path.join(base_path, current_name)

                            curr_vehicle_obj.save()
                        elif current_model == 2:
                            curr_vehicle_obj = Vehicle.objects.get(is_done=False, image_path=each_image)
                            current_name = str(curr_vehicle_obj.pk) + '_rc.jpg'
                            curr_vehicle_obj.rc_path = os.path.join(base_path, current_name)
                            curr_vehicle_obj.save()
                            # print(output_dict['detection_scores'][i])
                        # cv2.imshow('test', cv2.resize(image_np, (800, 600)))
                        # print(output_dict['detection_classes'][i])
                        coord = output_dict['detection_boxes'][i]
                        y1, x1, y2, x2 = coord[0], coord[1], coord[2], coord[3]
                        if class_name == 'motorcycle':
                            y1 -= ((y2 - y1) * motor_person_offset_percent / 100)
                            if y1 < 0:
                                y1 = 0
                        y1 = int(y1 * image_np.shape[0])

violation_detection/Interface/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">

<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Detection</title>

    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="author" content=""/>

    {% comment %} <link rel="stylesheet" href="../static/Interface/fonts/fontawesome-free-5.5.0-web/css/all.css"> {% endcomment %}
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <!--  Bootstrap CSS  -->
    <link rel="stylesheet" href="{% static 'Interface/css/bootstrap.css' %}">

    <!--    CSS  -->
    <link rel="stylesheet" href="{% static 'Interface/css/style.css' %}">
<style>
    .btn-circle.btn-lg {
      width: 50px;
      height: 50px;
      padding: 10px 16px;
      font-size: 18px;
      line-height: 1.33;
      border-radius: 25px;
    }

</style>
</head>

<body>
<div>
    <div>
        <!---Bootstrap Navbar -->
        <nav class="navbar navbar-expand-sm navbar-light bg-light justify-content-end navbar-fixed-top">
            <a class="navbar-brand" href="#">
                {#                <img src="/images/logo/QuickWash-navbar.svg" width="30" height="30" class="d-inline-block align-top">#}
                Traffic Rules Violation Detection
            </a>
            <div class="collapse navbar-collapse mr-auto" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active mr-auto navbar-right">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item navbar-right">
                        <a class="nav-link" href="#">Reciept</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Reports
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Daily</a>
                            <a class="dropdown-item" href="#">Monthly</a>
                            <a class="dropdown-item" href="#">Quaterly</a>
                        </div>
                    </li>
                    <li class="nav-item mr-auto">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <!---End of Bootstrap Navbar -->
    </div>

    <!-- Bootstrap sidebar -->

    {% block content %}

    {% endblock content %}

</div>
</body>

<!-- jQuery -->
<script src="{% static 'Interface/js/jquery.min.js' %}"></script>

<!-- Main -->
<script src="{% static 'Interface/js/main.js' %}"></script>

<!-- Bootstrap -->
<script src="{% static 'Interface/js/bootstrap.min.js' %}"></script>
<script src="{% static 'Interface/js/bootstrap.js' %}"></script>

<script src="{% static 'Interface/js/jquery.min.js' %}"></script>
<script src="{% static 'Interface/js/sidebar.js' %}"></script>
<script src="{% static 'Interface/js/bootstrap.min.js' %}"></script>
<script src="{% static 'Interface/js/bootstrap.js' %}"></script>
<!--
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
-->

{% block scripts %}

{% endblock scripts %}

</html>

violation_detection/Interface/templates/home.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
    <div align="center">
        <button class="btn btn-success" style="margin: 2.5%; size: 1.5em; border-radius: 30%;"
                onclick="sendPredictionRequest('1')">Start
        </button>
    </div>
    <div id="current_model" align="center" hidden>
        <h3>Current Model: </h3>
        <h3 id="model_name"></h3>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div id="model_1" hidden>
                <div id="progress_video">
                    <h3>Progress</h3>
                    <h3 id="frames_processed"></h3>
                    <div class="progress">
                        <div class="progress-bar progress-bar-success" role="progressbar" style="width:0%"
                             id="progress_1">

                        </div>
                    </div>
                </div>
                <div id="detected_objects"></div>
                <br/>
                <br/>
                <br/>
                <div align="center">
                    <button class="btn btn-primary btn-circle btn-lg" onclick="sendPredictionRequest('2')">>
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div id="model_2" hidden>
                <div id="progress_video">
                    <h4>Progress</h4>
                    <h4 id="frames_processed"></h4>
                    <div class="progress">
                        <div class="progress-bar progress-bar-success" role="progressbar" style="width:0%"
                             id="progress_2">

                        </div>
                    </div>
                </div>
                <div id="detected_objects"></div>
                <br/>
                <br/>
                <br/>
                <div align="center">
                    <button class="btn btn-primary btn-circle btn-lg" onclick="sendPredictionRequest('3')">>
                    </button>
                </div>

            </div>
            <div class="col-md-4">
                <div id="model_3" hidden>
                    <div id="progress_video">
                        <h3>Progress</h3>
                        <h3 id="frames_processed"></h3>
                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar" style="width:0%"
                                 id="progress_3">

                            </div>
                        </div>
                    </div>
                    <div id="detected_objects"></div>
                </div>
            </div>

        </div>
    </div>


{% endblock content %}

{% block scripts %}

    <script>
        var total_frames;
        var current_frame;

        function sendPredictionRequest(model_number) {
            $.ajax({
                type: 'POST',
                url: "{% url 'Interface:prediction' %}",
                data: {
                    'csrfmiddlewaretoken': "{{ csrf_token }}",
                    'model_name': model_number
                }
            });
            document.getElementById('current_model').hidden = false;
            document.getElementById('model_' + model_number).hidden = false;
            current_frame = model_number;
            get_first_response();
        }

        function get_first_response() {
            $.ajax({
                type: 'POST',
                url: "{% url 'Interface:get_first_response' %}",
                data: {
                    'csrfmiddlewaretoken': "{{ csrf_token }}",
                },
                success: function (data) {
                    let parsed = JSON.parse(data);
                    document.getElementById('model_name').innerHTML = parsed['model_name'];
                    total_frames = parseInt(parsed['total_frames']);
                    console.log(data);

                    get_frames();

                }
            })
        }

        function get_frames() {
            var interval = setInterval(function () {
                $.ajax({
                    type: 'POST',
                    url: "{% url 'Interface:get_frames' %}",
                    data: {
                        'csrfmiddlewaretoken': "{{ csrf_token }}",
                    },
                    success: function (data) {
                        let parsed_data = JSON.parse(data);
                        console.log(JSON.parse(data));
                        let total_frames = parseInt(parsed_data['total_frames']);

                        document.getElementById('frames_processed').innerHTML = parsed_data['frames_done'] + '/' + total_frames + ' frames';


                        let bar = document.getElementById('progress_'+ current_frame);
                        bar.innerHTML = (parseInt(parsed_data['frames_done']) / total_frames) * 100 + '%';
                        bar.setAttribute('style', 'width:' + (parseInt(parsed_data['frames_done']) / total_frames) * 100 + '%');

                        if (parsed_data['frames_done'] + 1 >= total_frames && total_frames != 0) {
                            clearInterval(interval);

                        }
                        {#bar.style.width = parseInt(parsed_data['frames_done']) / total_frames * 100;#}
                    }
                })
            }, 2000);

        }
    </script>
{% endblock scripts %}

violation_detection/Interface/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Detection</title>

      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Violation Detection</a>
        </div>
    </div>
</nav>

<div class="container">

    <!-- Main component for a primary marketing message or call to action -->
    <div class="jumbotron">

    </div>

</div> <!-- /container -->



</body>
</html>

violation_detection/Interface/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>QW | Login</title>

<!-- favicon -->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>

<!--  bootstrap -->
    <link rel="stylesheet" href="../static/Interface/css/bootstrap.min.css">
<!--Fonts awesome-->
	<link rel="stylesheet" type="text/css" href="../static/Interface/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--animate css-->
	<link rel="stylesheet" type="text/css" href="../static/Interface/css/animate/animate.css">
<!--hamburger css-->
	<link rel="stylesheet" type="text/css" href="../static/Interface/css/css-hamburgers/hamburgers.min.css">

    <link rel="stylesheet" type="text/css" href="../static/Interface/css/select2/select2.min.css">

	<link rel="stylesheet" type="text/css" href="../static/Interface/css/util.css">
	<link rel="stylesheet" type="text/css" href="../static/Interface/css/login.css">

</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="../static/Interface/images/img-01.png" alt="Computer Image">
				</div>

				<form class="login100-form validate-form">
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="#">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

<!--jquery-->
	<script src="../static/Interface/jquery/jquery-3.2.1.min.js"></script>

<!--bootstrap-->
	<script src="../static/Interface/js/popper.js"></script>
	<script src="../static/Interface/js/bootstrap.min.js"></script>

<!--select-->
	<script src="../static/Interface/css/select2/select2.min.js"></script>

<!--tilt -->
	<script src="../static/Interface/jquery/tilt/tilt.jquery.min.js"></script>

	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>

<!--main js-->
	<script src="../static/Interface/js/main.js"></script>

</body>
</html>